### ISSUE TITLE
Inconsistent terminology in Section 4.5.3.2

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#100]
Donald Eastlake wrote:

> Section 4.5.3.2: It seems confusing that the first paragraph talks
> about "each buffer of the data transfer" but there is only one mail
> data buffer at the server for a particular mail message and the
> subject of 4.5.3.2.5 uses "block" while the contents of 4.5.3.2.5
> uses "chunk" and "TCP SEND call"s.

**Comment by klensin** [comment]
Donald's analysis above is complicated by relay systems that start sending a message out before the incoming message has fully arrived and been confirmed.  See email discussion.

**Comment by klensin** [comment]
WG agreed at 2024-11-08 meeting to no change
