### ISSUE TITLE
Prohibition on MAIL FROM during transaction is unclear in Section 4.1.4

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#101]
Donald Eastlake wrote:

> Section 4.1.4, page 49, 3rd paragraph: This "MAIL MUST NOT be
> sent" text seems confusing at a minimum. To most readers MAIL is
> "being sent" with every RCPT command, with the DATA command, and
> with every new line of mail content. Please re-word it so it's
> something about "initiating" the sending of mail or the like.

To which John Klensin replied: 
> This is much like several cases where the WG decided to not change
> the text because the same wording (in this case, with the exception
> of removing discussion of SEND, SOML, and SAML) has been present
> since RFC 2821 and no actual issues with interoperability or even
> confusion have been demonstrated in more than 23 years.  I'm open
> to suggested text and discussion in the WG, but I fear that any
> improvements would be subject to confusion on other points.   As I
> reread it, I could see changing "MAIL MUST NOT be sent" to "message
> content MUST NOT be sent".  Would that help?  (Question addressed
> to the WG and community, not just Donald).

To which Alexey Melnikov replied:

> Actually, I think this changes the meaning. I read the original
> sentence as
> 
>    MAIL FROM command MUST NOT be sent if a mail transaction is already open ...
> 
> I.e. that this is prohibition on SMTP clients to reset a
> transaction with another MAIL FROM.

**Comment by klensin** [comment]
Alexey's comment matches a later one of Donald's nicely.   There is no such thing as a "MAIL FROM command", but Donald's suggestion of ""The MAIL command MUST..." works and is now in the working copy.  The WG should check but you can probably now mark this is "ready to be closed"

**Comment by aamelnikov** [comment]
Implemented in -33 and no objections voiced.
