### ISSUE TITLE
"required destination mailbox" in description of RCPT TO is unclear

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#106]
Donald Eastlake wrote:

>Section 4.1.1.3, 2nd paragraph: I think the word "required" should
>be deleted here as superfluous. It also reads a bit oddly.

The sentence in question is:

   The forward-path consists of the required destination mailbox.

**Comment by aamelnikov** [comment]
John Klensin replied:

>Unchanged since RFC 2821.  And I'm unwilling to decide that is
>is superfluous given some very odd historical cases.    WG?

To which Alexey Melnikov replied:

>I read "required destination mailbox" as "not allowed to be empty,
>like empty return path in MAIL FROM". So I would leave it as is.

**Comment by klensin** [comment]
Leave as is is fine.    If we need to make a change, consider "the destination mailbox name required by the syntax" as mentioned in the I-D (by version -33 ?) but minutes say "no appetite for change" on Nov 7 and no list discussion since.
