### ISSUE TITLE
Why is the requirement not to append extra info at the end of EHLO is only a SHOULD NOT?

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#107]
Paragraph 2 of Section 4.1.1.1 says:

   RFC 2821, and some earlier informal practices, encouraged following
   the literal by information that would help to identify the client
   system.  That convention was not widely supported, and many SMTP
   servers considered it an error.  In the interest of interoperability,
   it is probably wise for servers to be prepared for this string to
   occur, but SMTP clients SHOULD NOT send it.

Ted Lemon wrote:

>Non-DNS question: why is the "SHOULD NOT" in paragraph 2 of 4.1.1.1
>not a MUST NOT? What is the exception?

**Comment by aamelnikov** [comment]
John Levine replied:

>I don't think I've ever seen an EHLO with extra data.  I looked
>at the code for my mail server (mailfront) and it doesn't anticipate
>extra data in EHLO at all.  So I think we can say MUST NOT now.
>
>As you note, MTAs are always free to make their own decisions
>about what to accept but this seems very low risk.

**Comment by klensin** [comment]
Change made in working draft of 5321bis version 35.

For the information of anyone inclined to have second thoughts about this, the text in RFC 2821 is

>" [...] The argument field contains the fully-qualified domain name of the SMTP client if one is available. In situations in which the SMTP client system does not have a meaningful domain name (e.g., when its address is dynamically allocated and no reverse mapping record is available), the client SHOULD send an address literal (see section 4.1.3), optionally followed by information that will help to identify the client system."

So, if anyone other than me is still suffering mild anxiety over this change, an alternative would be to revert to the SHOULD and include a bit more of that explanation.  However, I will consider the matter closed unless someone else has comments.

**Comment by klensin** [comment]
Additional bullet point added to what is now Appendix E.1 explaining the new conformance requirement.

**Comment by aamelnikov** [comment]
Implemented in -35.
