### ISSUE TITLE
TURN (Appendix E.1)

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#108]
Should we further deprecate or prohibit TURN, or explain conditions under which it might be appropriate and be safely used?

See 2024-11-01 email message from Mike St. Johns, `<https://mailarchive.ietf.org/arch/msg/last-call/MGt0h6gsehKHRA4eY0zKc4C4r9U>`.

**Comment by klensin** [comment]
See `<https://mailarchive.ietf.org/arch/msg/emailcore/rcUeiodIxgUchmEZwU05GQQHcko>`  for further discussion, including reasons we might want to keep, rather than discard, TURN for very limited use, a brief analysis of the implications of trying to change rfc5321bis and/or push considerable material into the A/S, and an suggestion that this might best be kicked down the road and how.

**Comment by aamelnikov** [comment]
Proposal to leave the current text as is. If there is push back during IESG, change "TURN SHOULD NOT be used unless server can authenticate the client" to "...MUST NOT ..."

**Comment by klensin** [comment]
Incorporated in rfc5321bis version 33

**Comment by aamelnikov** [comment]
ETRN mentioned as an alternative in version 36.
