### ISSUE TITLE
In rfc5321bis, adding "(or HELO)" in more places

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#116]
Don Eastlake has suggested that the document would be improved by adding "(or HELO)" to more of the mentions/uses of of EHLO.    He believes this would be straightforward and said:

'Seems simple enough to me. There are ~83 occurrences of EHLO in the document. There are plenty of places where it is clear that EHLO is mentioned in relation to extensions, so HELO is irrelevant. And there are a number of places where "EHLO (or HELO)" is already used. For the remaining sections where EHLO is mentioned, I suggest replacing the first and only the first occurrence of "EHLO" in each of the following numbered sections with "EHLO (or HELO)":

     3.3
     4.1.1.5
     4.1.4
     4.2
     4.2.4.1
     4.2.4.2
     4.4.1 and
     4.4.3'

Does the WG want this done and, if so, who wants to check those sections and the other 75 or so to be sure he got it right?  If there is a counterargument beyond some variation of "been that way forever and has not caused problems", it would be that we want to say as little about HELO as possible

**Comment by aamelnikov** [comment]
I just checked the list and I think it should be:

3.3, 4.1.1.5, 4.1.4, 4.2.4.2, 4.4.1 and 4.4.5

**Comment by klensin** [comment]
So your list is different from Donald's list.  Do we now get three or four more people to check, see if their lists are different from either of yours, and then vote?  :-(

--or--

Should the difference cause us to acknowledge the reasons why we have been reluctant to make multiple-section small changes like this?  Those reasons include both the risk of getting it wrong and the absence of evidence that there has been any real confusion in the last couple of decades.  If we do, we might want to review Section 4.1.1.1 to see whether it, particularly the paragraph starting `"A client SMTP SHOULD start an SMTP..."` adequately makes the point that, while EHLO is strongly preferred,  HELO can be used anywhere that EHLO can except when extension support is needed.    If such new text were needed (I'm personally not yet convinced), more explanation  there would be far safer than trying to apply a small patch multiple times throughout the document.

**Comment by klensin** [comment]
Agreement at the meeting was that Arnt and Pete would check and try to come up with a single list on which they agreed.  They couldn't, so there are now four separate proposed lists -- Donald, Alexey, Arnt, Pete.  That strongly suggests that this is not as straightfo4rward as assumed and that this idea should be dropped and the question  above about the text in 4.1.1.1 addressed.  

Note that the point that adding "(or HELO)" is addressed by the last sentence of the second paragraph of 2.2.1, "Unless the different characteristics of HELO must be identified for interoperability purposes, this document discusses only EHLO."

[Further] deprecating HELO would address another aspect of this issue; see Ticket #123.

**Comment by aamelnikov** [comment]
My main concern is whether people can miss that HELO also resets the current transaction. It is kind of implied by existing text, but it is easy to miss.

**Comment by klensin** [comment]
I would be happy to make that change once it is clear that we are not going to try to sprinkle "(or HELO)" through the text.  Note added to working draft of version 36.

The change is to Section 3.3 and 4.1.1.5.   I hope there is nowhere else.

**Comment by klensin** [comment]
With no update on adding "(or HELO)" and where before 2024-12-01 (3 1/2 weeks after WG discussion and volunteers), much less evidence of any consensus, the fix to 5321bis to note that HELO closes existing transactions has been included in 5321bis-36.

**Comment by aamelnikov** [comment]
This is "ready to be closed" pending confirmation from the WG during the December 2024 interim meeting.

**Comment by aamelnikov** [comment]
The smaller change made in -36 looks acceptable to the WG.
