### ISSUE TITLE
Redundant "Standard or Standards-Track" in rfc5321bis Section 4.2

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#117]
rfc5321bis Section 4.2 (through -32) contains, in the paragraph starting "The list of codes that appears below". the phrase
"new Standards or Standards-Track specifications" appears.  In his review (and some convincing discussion in follow-up notes) he suggests removing "Standards or" as redundant given how "Standards-Track" is defined.

He is probably correct and the text has been tentatively changed, but the WG should check.

**Comment by aamelnikov** [comment]
Fixed in -33
