### ISSUE TITLE
An IANA registry for SMTP reply codes?

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#118]
In his review, Donald Eastlake strongly suggested that, instead of the explanation in Section 4.2, we create an IANA registry for SMTP reply codes.  He said, more or less, that the material in that section essentially defines allocation requirements and is therefore improper.  

His message at `<https://mailarchive.ietf.org/arch/msg/last-call/1qEIdmlXiDGhLkFnvEwppEZMfCs>` contains proposed XML for that registry.  

That message also contains additional discussion on this topic.

As I understand it, we have decided that we don't want any more codes, preferring that people invent new Extended Status Codes and use them with the existing base codes.   If circumstances arise that require new codes, it should be a big deal, presumably including an update to 5321bis.  If we decide to agree with Donald, then in addition to checking and updating his XML (at least one error/ issue is obvious), we need to create a new subsection of Section 7 on IANA considerations and figure out what should be moved there from Section 4.2.  We might conceivably also want to add some additional explicit requirements or recommendations for the relevant Standards Track documents (expert review + standards action?).

**Comment by aamelnikov** [comment]
The working group has discussed this and explicitly decided against creation of such registry.

**Comment by aamelnikov** [comment]
So this was closed with "no change".

**Comment by klensin** [comment]
According to the minutes, I was supposed to add a sentence suggesting use of enhanced status codes instead.  That recommendation was sort of already there, but confusion.   Adding the sentence required rewriting the paragraph.
