### ISSUE TITLE
rfc5321bis Gateway comments, Section 3.7, and Appendix D

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#119]
In his comments (see last part of `<https://mailarchive.ietf.org/arch/msg/last-call/1qEIdmlXiDGhLkFnvEwppEZMfCs>`), Donald Eastlake argues quite strongly that the text of Appendix D should be moved into Section 3.7 or at least that the appendix be referenced from 3.7.

Certainly such a change would push the minimum change requirements of the charter and the "intact since RFC2821 and no evidence of harm" principle, but we have moved text in 5321bis around before.  

Instructions?

**Comment by klensin** [comment]
Per discussion at WG meeting 2024-11-08, moved.   Note that the checking discussed at the meeting should include checking for whether references to subsequent appendices have been appropriately decremented.

**Comment by aamelnikov** [comment]
Implemented in -35.
