### ISSUE TITLE
Does Section 6.1 of rfc5321bis sound normative rather than as strong advice and, if so, how should that be fixed?

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#122]
(Split off from Ticket #114, really a separate issue.  However, there is some discussion of this issue as part of #114 before the split, so people should look there for context as needed.)

After the WG meeting had concluded on 2024-11-08, Dave Crocker posted a note objecting to the use of "MUST" in the base document (as with the rest of the text discussed in Ticket #114, inherited from RFC 1123).  His proposed replacement text appears in 
&lt;https://mailarchive.ietf.org/arch/msg/emailcore/JQkDT6mGyc_MhFei4RHSDt8cwrs&gt;
and below and has been included as a comment in rfc5321bis-35.

His proposed text is:

> 'When the receiver-SMTP sends a "250 OK", in response to a DATA command, they are accepting responsibility for delivering that piece of mail, for relaying to the next email handling agent that takes further responsibility for it, or for judiciously deciding to discard the message, possibly also returning a failure notification to the SMTP Mail From address. Responsibility includes robustness against predictable loss, such as reboots, server crashes, disk failures, or resource shortages.'

If I've got this right, the justification for the alternate version was that the presence of "MUST" in the 5321bis text (as well as the Bron/Todd text discussed in Ticket #114 and in RFCs 2821 and 1123)  created a normative requirement and that is unacceptable because there is no technical basis for testing conformance (or any other basis for that matter).    That requirement, while probably reasonable, has no basis in BCP 14 or BCP 9.

So the question for the WG is whether the Bron/Todd text with "MUST"  (see ticket #114) (or the original, or the Eastlake text) is acceptable and, if not, whether the best fix is the text quoted above (or a revised version), the Bron/Todd text with "MUST" dropped to lower case, or something else?

**Comment by aamelnikov** [comment]
At December 2024 interim there was a preference to keep the MUST. So no changes for this ticket.
