### ISSUE TITLE
Should HELO be deprecated?

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#123]
Building on the discussion on Ticket #116 and brief comments during the meeting, should HELO be deprecated?  I.e., should the paragraph starting "A client SMTP SHOULD start an SMTP session by issuing the EHLO command" and the discussion in 2.2.1 tweaked to say that clients SHOULD NOT send HELO although servers are still required to recognize and support it.

This is a smaller change than has been assumed in some recent discussions as the text goes most of the way toward that already.  E.g., 2.2.1 says "clients SHOULD preferentially utilize EHLO rather than HELO" 

If this chance is made, the change in requirements should be noted in Appendix E.1

**Comment by aamelnikov** [comment]
This issue was discussed at the December 2024 interim and there doesn't seem to be any appetite in the WG to do the change.
