### ISSUE TITLE
"other contemporary standards" in Section 2.3.1 of rfc5321bis-35

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#124]
In a Last Call review [1], Vijay Gurbani wrote:

> > - S2.3.1, last paragraph, sentence starting with "If the content
> conforms to other contemporary standards...": I find this sentence
> hard to understand; what is it that we are saying?  Are we saying
> that we expect the content to be like other IETF standards where we
> have a number of headers (header-name COLON header-value), followed
> by a blank line (\r\n) followed by the data that consists the body?
> If so, then we should have references to the nebulous "other
> contemporary standards".
> 
> As a developer, I would have no idea what I should be doing if the
> content DOES NOT conform to "other contemporary standards".

Klensin comment:

This was deliberately vague to avoid the implication that messages structured according to  RFC 822 - 5322bis were the only valid content that could be transported and, more important, to avoid turning MIME into a requirement for mail to be transported over SMTP.   It was also probably more important before we deprecated SEND/ SAML/ SOML.  But SMTP is still used in devices (mostly older ones that we would describe as "IoT" today) to transmit notifications or the like without full header information.

Options: 
(1) Invoke the "old text" principle.   This text is identical to that in RFC 5321 other than updating of references and small editorial corrections.  Indeed, the 5321 text is the same as that in 2821 with the exception of wording changes  to make things more clear and move on.

(2) Make "other contemporary standards" read "other contemporary standards such as the message format specification (rfc5322bis) and MIME (rfc2045)" and then edit the rest of the sentence as needed.

Author recommendation: No change, with the understanding the is motivated partially by laziness.  But the WG should, if possible, decide about this.  

[1] <https://mailarchive.ietf.org/arch/msg/emailcore/kB1CNtf0-hY4mUlFnBD5_jp2uSE>

**Comment by aamelnikov** [comment]
John has proposed 2 variants on how to make it clearer that payloads other than header + body can be transported by SMTP. This was discussed at the December 2024 interim. The second proposal was incorporated into -37.
