### ISSUE TITLE
Rearrange Section 4.1.1.4 of rfc5321bis-35 (again)

### ISSUE THREAD

**Issue by klensin** [ietf-wg-emailcore/emailcore#125]
In a Last Call review [1], Vijay Gurbani wrote:

> - S4.1.1.4, fourth paragraph: The specification states that "The
> SMTP model does not allow for partial failures at this point:",
> however, in the sixth paragraph starts with "The server must give
> special treatment to cases in which processing ... is only
> partially successful."  I understand the intent of the fourth
> paragraph: the server sending a 250 OK takes responsibility of
> delivering the message to the recipients, and if it cannot, an
> "undeliverable mail" notification is sent (as per the sixth
> paragraph).  But developers reading this may be a tad confused.
> Would it make sense to move the sixth paragraph to be under the
> current fourth paragraph, and start it with "Under certain
> circumstances, the server must give special treatment ... of the
> message."

Klensin comment:
I am exhausted on this subject after other discussions, analyses of the effects of parts of Sections 6 and 7, paragraph rearrangements in this Section, etc.   No recommendation other than that these rearrangements have often been shown to have unanticipated side effects so anyone wanting a rearrangement should volunteer to carefully check for other implications in the document first.   If there are no further comments, default is presumably "no change".

[1] <https://mailarchive.ietf.org/arch/msg/emailcore/kB1CNtf0-hY4mUlFnBD5_jp2uSE>

**Comment by aamelnikov** [comment]
The current text says:

4th para:
   Receipt of the end of mail data indication requires the server to
   process the stored mail transaction information.  This processing
   consumes the information in the reverse-path buffer, the forward-path
   buffer, and the mail data buffer, and on the completion of this
   command these buffers are cleared.  If the processing is successful,
   the receiver MUST send an OK reply.  If the processing fails, the
   receiver MUST send a failure reply.  The SMTP model does not allow
   for partial failures at this point: either the message is accepted by
   the server for delivery and a positive response is returned or it is
   not accepted and a failure reply is returned (see Section 4.4.3 for
   additional discussion).  In sending a positive "250 OK" completion
   reply to the end of data indication, the receiver takes full
   responsibility for the message (see Section 6.1).  Errors that are
   diagnosed subsequently MUST be reported in a mail message.

5th para:
   When the SMTP server accepts a message either for relaying or for
   final delivery, it inserts a trace record (also referred to
   interchangeably as a "time stamp line", "Received" line, or
   "Received:" header field) at the top of the mail data.  This trace
   record indicates the identity of the host that sent the message, the
   identity of the host that received the message (and is inserting this
   time stamp), and the date and time the message was received.  Relayed
   messages will have multiple time stamp lines.  Details for formation
   of these lines, including their syntax, is specified in Section 4.4.

6th para:
   The server must give special treatment to cases in which processing
   following the end of mail data indication is only partially
   successful.  This could happen if, after accepting several recipients
   and the mail data, the SMTP server finds that the mail data could be
   successfully delivered to some, but not all, of the recipients.  In
   such cases, the response to the DATA command MUST be an OK reply.
   However, the SMTP server MUST compose and send an "undeliverable
   mail" notification message to the originator of the message.

The suggestion is to move 6th para before the 4th para.

**Comment by aamelnikov** [comment]
Implemented in -37.
