### ISSUE TITLE
Restricted-capability clients?

### ISSUE THREAD

**Issue by jrlevine** [ietf-wg-emailcore/emailcore#60]
Sec 3.3 refers to restricted-capability clients. I think that's what we now call submission, so we can take that out and just say clients MUST NOT use source routes.

**Comment by aamelnikov** [comment]
Further discussion at IETF 113 brought a question: is this about prohibiting open relays?

**Comment by aamelnikov** [comment]
Mailing list discussion thread: https://mailarchive.ietf.org/arch/msg/emailcore/XtKLDF7MezR4FUd22x8OFWT-f5k/

**Comment by jrlevine** [comment]
I realize that a typical restricted-capability client is my printer, which I can configure to send alerts to one or two fixed email addresses at a single fixed server. So that server either has to be the MTA that handles the addresses or a submission server. Yes, it's basically about not expecting open relays.

**Comment by aamelnikov** [comment]
"No open relays" text is be better in A/S. Might need to open a separate ticket about that

**Comment by aamelnikov** [comment]
Text clarified in -12.
