### ISSUE TITLE
VRFY in required commands in 4.5.1

### ISSUE THREAD

**Issue by jrlevine** [ietf-wg-emailcore/emailcore#63]
Nobody implements VRFY any more other than by always responding 252. It seems pointless still to require it.

**Comment by jrlevine** [comment]
But it's harmless, and trivial to implement a version that replies 252 to everything so it's more trouble than it's worth to take out.

**Comment by aamelnikov** [comment]
Proposal from IETF 113 is no change in base spec, but can discuss on mailing list the idea of putting extra text in A/S

**Comment by aamelnikov** [comment]
Separately, there was a suggestion to register VRFY with IANA. It used to be a separate extension and it would be good to have it in the IANA registry.

**Comment by aamelnikov** [comment]
Registration of VRFY with IANA added in -11.
