### ISSUE TITLE
G.22. IANA Registration Model for Registries Other Than Service Extensions

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#76]
John Klensin wrote:

   The WG decided to shift the registration model for Service Extensions
   from "Standards Track or IESG-approved Experimental" to
   "Specification Required".  No decisions have been made yet about
   other mail-related registries established by this document in
   Section 8.1.  They will be left unchanged, and this item closed
   unless other decisions are made, presumably before IETF 115.
   Probably ready to close.

**Comment by aamelnikov** [comment]
Summary of current registration procedures for remaining registries:

8.1.2.  Address Literal Tags

   Additional literal types require standardization before
   being used; none are anticipated at this time.

-- Alexey: not very specific

8.1.3.  Mail Transmission Types

   The third, "Mail Transmission Types" [58], established by RFC 821 and
   renewed by this specification, is a registry of link and protocol
   identifiers to be used with the "via" and "with" subclauses of the
   time stamp ("Received:" header field) described in Section 4.4.  Link
   and protocol identifiers in addition to those specified in this
   document may be registered only by standardization or by way of an
   RFC-documented, IESG-approved, Experimental protocol extension.

8.1.4.  Additional Registered Clauses

   As mentioned in Section 4.4.1 above, additional clauses for the
   "Received:" header field may be added by future standards track
   specifications.

-- Alexey: the above is not fully consistent with what follows:

   Additional clauses may be registered only by
   standardization or by way of an RFC-documented, IESG-approved,
   Experimental protocol extension.

**Comment by klensin** [comment]
The inconsistent language in 8.1.4 has been fixed by an application of the 'in only one place" principle to the working version of rfc5321bis-16.

For 8.1.3, see Editor's Analysis in [https://mailarchive.ietf.org/arch/msg/emailcore/NVd2BdnLkURNjLaSG3S6rqXJY0s](url).

**Comment by aamelnikov** [comment]
Interim suggested the following:

  Address Literal Tags: "Standards Action" (the only value currently 
  registered is "IPv6")

  Values of the WITH clause of the Received Header Field: "RFC Required"

  Values of the VIA clause of the Received Header Field: "RFC Required"

  Additional Registered Clauses: "IETF Review"

Summary of the interim posted to the mailing list: https://mailarchive.ietf.org/arch/msg/emailcore/7LtG9LnXxi8CGdqz_qG0hBiI7oo/

No objections received to the proposal.

**Comment by aamelnikov** [comment]
Sent email stating that I intend to close this ticket on 13/02/2023.
