### ISSUE TITLE
IANA registration procedure for Trace Header Fields?

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#81]
Do we want a separate registry? If we do, how does this interact with existing registry of Header Fields? (I.e. do we pull them out?)
If not, do we want to add information about trace header fields as comments in the Header Field registry? Or we can just do nothing (i.e. don't keep this information anywhere).

**Comment by gklyne** [comment]
_Not sure that I'll make the emailcore meeting this week, so commenting here..._

_For background, I'm the IANA reviewer for the message header registry, and also a co-editor of the original message header registration procedure.  But other than that, I'm not deeply involved in current IETF discussions, so my comments may overlook some context._

One of the purposes of the header field registry is to provide a single point of search for anyone thinking about creating a new field, or trying to find what is available.  Fragmenting the registry dilutes that benefit.

I see no particular problem with adding additional information pertinent to trace fields to the existing message header template (maybe used only/primarily for trace fields).

**Comment by jrlevine** [comment]
I thought we agreed we could add a column saying whether a header is a trace or not. Seems far easier than anything else.

**Comment by aamelnikov** [comment]
@jrlevine I think this is still the plan.

**Comment by aamelnikov** [comment]
Implemented in draft-ietf-emailcore-rfc5322bis-06.
