### ISSUE TITLE
Add text about handling of Trace Header Fields by MUAs

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#84]
Suggested addition:

  A MUA that uses an existing email message as a template for editing
  with the intention of sending it to new set of recipients (this is
  sometimes implemented as "edit as a new message" feature) SHOULD
  strip trace header fields.

**Comment by aamelnikov** [comment]
Seem to be supported by the discussion in the following thread <https://mailarchive.ietf.org/arch/msg/emailcore/gQ8VfvHRhpDhuWzsfvaF0W640t8>

**Comment by ksmurchison** [comment]
Added the proposed test to draft -10

**Comment by ksmurchison** [comment]
Klensin proposed some text/questions: [https://mailarchive.ietf.org/arch/msg/emailcore/DgPgxqJbwB6X9_Tlc6ilch8j0T0/](url)

**Comment by ksmurchison** [comment]
The following text crafted by Pete and Ken has been added to -12:

```
3.3.  Reuse of Existing Messages

   Many mail user agents (MUAs) have functions which use an existing
   email message as a template for editing a new message.  For example,
   an MUA may take an existing message, allow the user to replace the
   originator and destinations, edit parts of the body, and send it on
   to the new recipients.  When performing such functions, the MUA
   SHOULD:

   *  Remove all header fields unknown to the MUA
   *  Remove any header fields that are only pertinent to the transport
      of the original message, such as trace header fields (see
      Section 3.6.7 of [I-D.ietf-emailcore-rfc5322bis])
```
