### ISSUE TITLE
Expand on operational meaning of being a trace header field

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#86]
Pete Resnick wrote:

Right now, being a trace field is syntactically to be part of the Return-Path/Received block, and semantically means to be information about this messages movement through the system from submission to delivery. But what is the operational meaning? Is the only operational implication of being a trace field that you delete it in certain circumstances (like edit-as-new, mailing list distribution, etc.), or does it mean something more than that? 

If it only means "delete on MUA resend" (or some variant of that), then the registry should probably be labeled that instead of "trace". If it means something more than that, then the A/S should probably have a much richer discussion than text suggested for ticket #84.

**Comment by ksmurchison** [comment]
Consensus at IETF 120 was to do nothing in the A/S
