### ISSUE TITLE
SHOULD level requirement on users in 4.2.4.3

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#90]
Alexey Melnikov wrote:

4.2.4.3.  Reply Codes after DATA and the Subsequent
<CRLF>.<CRLF>

  The user who originated the message SHOULD be able to
interpret the

I find it odd to have RFC 2119 level requirement on users.
Maybe change "SHOULD" to the lowercase "should", if we really
talking about users here?

**Comment by aamelnikov** [comment]
Is this talking about server operators? Then SHOULD might be more appropriate.

**Comment by toddherr** [comment]
As an example...

The operator of the SMTP server SHOULD endeavor to use text in the transient failure status that is clear to the originator of the message in its meaning as a non-delivery indication....

**Comment by aamelnikov** [comment]
2 suggested replacements:

    The operator of an SMTP server SHOULD use text in
    the transient failure status (by mail message or otherwise)
    that can reasonably be expected to be interpreted by
    the originator as a non-delivery indication, just as a permanent
    failure would be interpreted. If the client SMTP successfully
    handles these conditions, the user will not receive such a reply.

Or:

    An SMTP response indicating a transient failure status SHOULD
    contain text providing a simple explanation, indicating that
    delivery of the message is delayed.

**Comment by klensin** [comment]
See extended discussion at https://mailarchive.ietf.org/arch/msg/emailcore/2Soh8oWadOnpIIiHLVE_LIDLNxc  .  That discussion includes an example that illustrates why the second option above does not work.   If the  "transient failure" indication reaches the message originator, it is, as far as the mail system is concerned, a permanent error, not, e.g., an indication that there was a delay but delivery attempts are continuing.

**Comment by aamelnikov** [comment]
After a further discussion, the following proposal was made by John Klensin:

   The text provided by the server as part of the reply SHOULD be
   designed to allow the user, or the user's agent, to interpret the
   return of a transient failure status (by mail message or otherwise)
   as a non-delivery indication, just as a permanent failure would be
   interpreted.  If the client SMTP successfully handles these
   conditions, the user will not receive such a reply.

Subsequent explanation from John pointed out why this needs to be a SHOULD and why we don't want to go into details of explaining this, as this might take weeks to figure out and write correctly.

**Comment by aamelnikov** [comment]
Implemented in -28
